# Generated by Django 5.2.5 on 2025-10-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
