# Generated by Django 5.2.5 on 2025-10-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_teacher_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
    ]
