# Generated by Django 5.2.5 on 2025-10-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('GCSE', 'GCSE'), ('A-Level', 'A-Level'), ('O-Level', 'O-Level'), ('AS-Level', 'AS-Level'), ('AQA', 'AQA'), ('BSc', 'BSc'), ('MSc', 'MSc'), ('PhD', 'PhD')], default='GCSE', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Face-to-Face', 'Face-to-Face')], default='Online', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='psw_eligible',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
